### ISSUE TITLE
Deployment node feature request

### ISSUE THREAD

**Issue by madreason** [kaminzo/c4-draw.io#2]
The deployment node is container with description in left bottom angle, node count in right bottom angle, solid border, slightly rounded edges.

![deploy node](https://user-images.githubusercontent.com/1410761/97689421-987da400-1aac-11eb-979d-66f2bfbd58af.png)

**Comment by seanchann** [comment]
any progress?

**Comment by madreason** [comment]
> any progress?

You can try this lib.

https://github.com/madreason/c4-diagrams.net

**Comment by kaminzo** [comment]
Thanks for the hint and idea of how to add this @madreason.
It is reflected in the recent change.
